### ISSUE TITLE
Version 3.7.5 crashes on device without Google Play Services

### ISSUE THREAD

**Issue by articlecat** [meganz/android#109]
MEGA version 3.7.5 (305) crashes on my device immediately after logging in. The "Add phone number" prompt shows for a moment, and then the app crashes. Upon reopening the MEGA app, after updating/preparing the file list, it shows the list of files for a moment before crashing again.

My device runs Android 9, and uses [MicroG](https://github.com/microg/android_packages_apps_GmsCore/blob/master/README.md) instead of Google Play Services. The logcat exception indicates that the crash is associated with MEGA's BillingManager:

```
FATAL EXCEPTION: main
Process: mega.privacy.android.app, PID: 24284
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at mega.privacy.android.app.utils.billing.BillingManager$5.run(BillingManager.java:332)
	at mega.privacy.android.app.utils.billing.BillingManager.executeServiceRequest(BillingManager.java:382)
	at mega.privacy.android.app.utils.billing.BillingManager.queryPurchases(BillingManager.java:344)
	at mega.privacy.android.app.utils.billing.BillingManager.access$100(BillingManager.java:54)
	at mega.privacy.android.app.utils.billing.BillingManager$1.run(BillingManager.java:127)
	at mega.privacy.android.app.utils.billing.BillingManager$6.onBillingSetupFinished(BillingManager.java:362)
	at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection$1.run(com.android.billingclient:billing@@2.1.0:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Version 3.7.4 (300) does not have this issue.

**Comment by javiergm1983** [comment]
Hi @articlecat, we have already applied a patch for this issue in the v3.7.5 (307). Thanks for report it.
Please, let us to know if it works properly in your case. Thanks.

**Comment by articlecat** [comment]
Version 3.7.5 (307) works perfectly. Thank you @javiergm1983 for addressing the issue so quickly!
