### ISSUE TITLE
Crash [With logs up to the crash]

### ISSUE THREAD

**Issue by Thewisem** [meganz/android#150]
## General Information

- **MEGA Version:** 

- **OS Version(s):** 

- **Devices/Simulators:** 

- **Reproducible? (Yes/No):**  Yes

##  What happened?
...
Crash
FATAL EXCEPTION: main
Process: com.farmerbb.notepad, PID: 5598
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 808968 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4238)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: android.os.TransactionTooLargeException: data parcel size 808968 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:628)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4206)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4230)
	... 7 more
## What did you expect to happen?
... Not crash

**Comment by sakethv-mega** [comment]
Hello there,

Thanks for reporting the crash.

We would like to investigate this issue further.

Can you please give us the exact steps to reproduce this issue? 
 
Also, we need the logs from the generated the app for further analysis as the logs you have provided from the Logcat console are not entirely helpful.

Please open the MEGA app, go to `Settings` and tap 5 times on `MEGAchat SDK version` - the logging will be enabled.

Then go to your Cloud Drive and try to reproduce the issue you are experiencing with the latest version.

After creating the logs disable them again by tapping 5 times on the `MEGAchat SDK version`.
We recommend you to disable the logs after testing since the file can be quite large if kept enabled.

The log files will be stored at-> 
/sdcard/MEGA/MEGA Logs/logKarere.txt  

or 
/My Files/Device Storage/MEGA/MEGA logs/logKarere.txt  

Please send us the file for examination.

Also please advise your device details and version of your operating system.

IF YOU CAN NOT OPERATE THE APP:
In your Android device Settings 
Go to Apps
Find MEGA and tap on it
Tap on Storage
Tap CLEAR DATA and CLEAR CACHE

Then kill the app and reopen.

Then follow the steps above and advise us of the result and send us logs.

If the log file is too large, you can upload it to MEGA and send us the MEGA link to the file.

Thank you.

**Comment by Thewisem** [comment]
I did that and I got those logs. It seems it wasn't helpful. Reproducing the crash will make the same log again

**Comment by Thewisem** [comment]
I had made the logs in a previous issue. But it wasn't helpful

**Comment by sakethv-mega** [comment]
Hello there, just enable logging on the app, try to reproduce the crash so that the app logs can record it, and send the logs to us.
Also, please list out the exact steps to reproduce the crash so that we can try it on our end too.
Thank you.

**Comment by sakethv-mega** [comment]
Ping @Thewisem in case you are still keen to send the logs to us. Thank you.

**Comment by Thewisem** [comment]
[logSDK.txt](https://github.com/meganz/android/files/6949050/logSDK.txt)
[logKarere.txt](https://github.com/meganz/android/files/6949051/logKarere.txt)

**Comment by Thewisem** [comment]
Here

**Comment by Thewisem** [comment]
If you want to reproduce it,
Create a mega drive and then a folder. paste 1000-3000 photos. Configure in vertical way and not the horizontal one(where the picture previews are bigger).
Then open that folder and slowly scroll down. Just do it for some time. Then do it a little bit faster(optional). And crash

**Comment by sakethv-mega** [comment]
Thanks for sending the logs and the steps through to us. We have forwarded them to our developers for further investigation. Thank you.
